version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: hogwarts-laravel-db
        environment:
            POSTGRES_DB: hogwarts
            POSTGRES_USER: wizard
            POSTGRES_PASSWORD: magic123
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - hogwarts-laravel-net

volumes:
    pgdata:

networks:
    hogwarts-laravel-net:
        driver: bridge